# Generated by Django 6.0.6 on 2026-07-04 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipoevento',
            fields=[
                ('idtipoevento', models.AutoField(db_column='idTipoEvento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('desactivataller', models.IntegerField(blank=True, db_column='desactivaTaller', null=True)),
                ('borrado', models.IntegerField(db_column='borrado')),
            ],
            options={
                'db_table': 'tipoevento',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idevento', models.AutoField(db_column='idEvento', primary_key=True, serialize=False)),
                ('fechadesde', models.DateField(blank=True, db_column='fechaDesde', null=True)),
                ('fechahasta', models.DateField(blank=True, db_column='fechaHasta', null=True)),
                ('motivo', models.CharField(blank=True, max_length=256, null=True)),
                ('borrado', models.IntegerField(db_column='borrado')),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.personaep')),
                ('idtipoevento', models.ForeignKey(db_column='idTipoEvento', on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.tipoevento')),
            ],
            options={
                'db_table': 'evento',
            },
        ),
    ]
