# Generated by Django 6.0.6 on 2026-09-03 15:42

from django.db import migrations, models


def verificar_y_convertir_borrado(apps, schema_editor):
    for model_name in ('Evento', 'Tipoevento'):
        Modelo = apps.get_model('eventos', model_name)
        valores = set(v['borrado'] for v in Modelo.objects.values('borrado').distinct())
        if not valores.issubset({0, 1}):
            raise RuntimeError(
                f"Valores inesperados en eventos.{model_name}.borrado: {sorted(valores)}. "
                "Se esperaban únicamente 0 y 1; migración abortada sin cambios."
            )
        Modelo.objects.filter(borrado=0).update(borrado=False)
        Modelo.objects.exclude(borrado=0).update(borrado=True)


def revertir_borrado(apps, schema_editor):
    for model_name in ('Evento', 'Tipoevento'):
        Modelo = apps.get_model('eventos', model_name)
        Modelo.objects.filter(borrado=False).update(borrado=0)
        Modelo.objects.exclude(borrado=False).update(borrado=1)


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(verificar_y_convertir_borrado, revertir_borrado),
        migrations.AlterField(
            model_name='evento',
            name='borrado',
            field=models.BooleanField(db_column='borrado', default=False),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='borrado',
            field=models.BooleanField(db_column='borrado', default=False),
        ),
    ]
