# Generated by Django 6.0.6 on 2026-09-03 23:31

from django.db import migrations, models


def verificar_y_convertir_desactivataller(apps, schema_editor):
    Tipoevento = apps.get_model('eventos', 'Tipoevento')
    valores = set(v['desactivataller'] for v in Tipoevento.objects.values('desactivataller').distinct())
    if not valores.issubset({0, 1}):
        raise RuntimeError(
            f"Valores inesperados en eventos.Tipoevento.desactivataller: {sorted(valores)}. "
            "Se esperaban únicamente 0 y 1; migración abortada sin cambios."
        )
    Tipoevento.objects.filter(desactivataller=0).update(desactivataller=False)
    Tipoevento.objects.exclude(desactivataller=0).update(desactivataller=True)


def revertir_desactivataller(apps, schema_editor):
    Tipoevento = apps.get_model('eventos', 'Tipoevento')
    Tipoevento.objects.filter(desactivataller=False).update(desactivataller=0)
    Tipoevento.objects.exclude(desactivataller=False).update(desactivataller=1)


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_borrado_alter_tipoevento_borrado'),
    ]

    operations = [
        migrations.RunPython(verificar_y_convertir_desactivataller, revertir_desactivataller),
        migrations.AlterField(
            model_name='tipoevento',
            name='desactivataller',
            field=models.BooleanField(db_column='desactivaTaller', default=False),
        ),
    ]