# Generated by Django 6.0.6 on 2026-10-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_tipoevento_desactivataller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fechadesde',
            new_name='fecha_desde',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='fechahasta',
            new_name='fecha_hasta',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='idevento',
            new_name='id_evento',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='idpersonaep',
            new_name='persona_ep',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='idtipoevento',
            new_name='tipo_evento',
        ),
        migrations.RenameField(
            model_name='tipoevento',
            old_name='desactivataller',
            new_name='desactiva_taller',
        ),
        migrations.RenameField(
            model_name='tipoevento',
            old_name='idtipoevento',
            new_name='id_tipo_evento',
        ),
        migrations.AlterModelTable(
            name='evento',
            table='eventos_evento',
        ),
        migrations.AlterModelTable(
            name='tipoevento',
            table='eventos_tipo_evento',
        ),
    ]
