# Generated by Django 6.0.6 on 2026-10-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_rename_fechadesde_evento_fecha_desde_and_more'),
        ('personas', '0020_alter_departamento_id_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id_evento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='persona_ep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personas.personaep'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.tipoevento'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='desactiva_taller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='id_tipo_evento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
