# Generated by Django 6.0.6 on 2026-07-04 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasetaller',
            fields=[
                ('idclasetaller', models.AutoField(db_column='idClaseTaller', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('virtual', models.IntegerField()),
            ],
            options={
                'db_table': 'clasetaller',
            },
        ),
        migrations.CreateModel(
            name='Comportamiento',
            fields=[
                ('idcomportamiento', models.AutoField(db_column='idComportamiento', primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'comportamiento',
            },
        ),
        migrations.CreateModel(
            name='Factorglobal',
            fields=[
                ('idfactorglobal', models.AutoField(db_column='idFactorGlobal', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'factorglobal',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('idtaller', models.AutoField(db_column='idTaller', primary_key=True, serialize=False)),
                ('tipotaller', models.CharField(db_column='tipoTaller', max_length=45)),
            ],
            options={
                'db_table': 'taller',
            },
        ),
        migrations.CreateModel(
            name='Unidadobservacion',
            fields=[
                ('idunidadobservacion', models.AutoField(db_column='idUnidadObservacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'unidadobservacion',
            },
        ),
        migrations.CreateModel(
            name='Asistenciataller',
            fields=[
                ('idasistenciataller', models.AutoField(db_column='idAsistenciaTaller', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=45)),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.personaep')),
                ('idclasetaller', models.ForeignKey(db_column='idClaseTaller', on_delete=django.db.models.deletion.DO_NOTHING, to='talleres.clasetaller')),
                ('idcomportamiento', models.ForeignKey(blank=True, db_column='idComportamiento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='talleres.comportamiento')),
            ],
            options={
                'db_table': 'asistenciataller',
            },
        ),
        migrations.AddField(
            model_name='clasetaller',
            name='idtaller',
            field=models.ForeignKey(db_column='idTaller', on_delete=django.db.models.deletion.DO_NOTHING, to='talleres.taller'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idactividad', models.AutoField(db_column='idActividad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('idtaller', models.ForeignKey(db_column='idTaller', on_delete=django.db.models.deletion.DO_NOTHING, to='talleres.taller')),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Variableuo',
            fields=[
                ('idvariableuo', models.AutoField(db_column='idVariableUO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('idcomportamiento', models.ForeignKey(db_column='idComportamiento', on_delete=django.db.models.deletion.DO_NOTHING, to='talleres.comportamiento')),
                ('idunidadobservacion', models.ForeignKey(db_column='idUnidadObservacion', on_delete=django.db.models.deletion.DO_NOTHING, to='talleres.unidadobservacion')),
            ],
            options={
                'db_table': 'variableuo',
            },
        ),
        migrations.CreateModel(
            name='Valorvariableuo',
            fields=[
                ('idvalorvariableuo', models.AutoField(db_column='idValorVariableUO', primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=45)),
                ('idvariableuo', models.ForeignKey(db_column='idVariableUO', on_delete=django.db.models.deletion.DO_NOTHING, to='talleres.variableuo')),
            ],
            options={
                'db_table': 'valorvariableuo',
            },
        ),
        migrations.CreateModel(
            name='Actividadrealizada',
            fields=[
                ('idactividad', models.OneToOneField(db_column='idActividad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='talleres.actividad')),
                ('idclasetaller', models.ForeignKey(db_column='idClaseTaller', on_delete=django.db.models.deletion.DO_NOTHING, to='talleres.clasetaller')),
            ],
            options={
                'db_table': 'actividadrealizada',
                'unique_together': {('idactividad', 'idclasetaller')},
            },
        ),
        migrations.CreateModel(
            name='Factorclase',
            fields=[
                ('idclasetaller', models.OneToOneField(db_column='idClaseTaller', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='talleres.clasetaller')),
                ('idfactorglobal', models.ForeignKey(db_column='idFactorGlobal', on_delete=django.db.models.deletion.DO_NOTHING, to='talleres.factorglobal')),
            ],
            options={
                'db_table': 'factorclase',
                'unique_together': {('idclasetaller', 'idfactorglobal')},
            },
        ),
    ]
