# Generated by Django 6.0.6 on 2026-08-23 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_localidad_id_georef_municipio_id_georef_and_more'),
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadrealizada',
            name='idclasetaller',
            field=models.ForeignKey(db_column='idClaseTaller', on_delete=django.db.models.deletion.CASCADE, to='talleres.clasetaller'),
        ),
        migrations.AlterField(
            model_name='asistenciataller',
            name='idclasetaller',
            field=models.ForeignKey(blank=True, db_column='idClaseTaller', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talleres.clasetaller'),
        ),
        migrations.AlterField(
            model_name='asistenciataller',
            name='idpersonaep',
            field=models.ForeignKey(blank=True, db_column='idPersonaEP', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.personaep'),
        ),
        migrations.AlterField(
            model_name='factorclase',
            name='idclasetaller',
            field=models.OneToOneField(db_column='idClaseTaller', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='talleres.clasetaller'),
        ),
    ]
