# Generated by Django 6.0.6 on 2026-09-03 23:31

from django.db import migrations, models


def verificar_y_convertir_virtual(apps, schema_editor):
    Clasetaller = apps.get_model('talleres', 'Clasetaller')
    valores = set(v['virtual'] for v in Clasetaller.objects.values('virtual').distinct())
    if not valores.issubset({0, 1}):
        raise RuntimeError(
            f"Valores inesperados en talleres.Clasetaller.virtual: {sorted(valores)}. "
            "Se esperaban únicamente 0 y 1; migración abortada sin cambios."
        )
    Clasetaller.objects.filter(virtual=0).update(virtual=False)
    Clasetaller.objects.exclude(virtual=0).update(virtual=True)


def revertir_virtual(apps, schema_editor):
    Clasetaller = apps.get_model('talleres', 'Clasetaller')
    Clasetaller.objects.filter(virtual=False).update(virtual=0)
    Clasetaller.objects.exclude(virtual=False).update(virtual=1)


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_alter_actividadrealizada_idclasetaller_and_more'),
    ]

    operations = [
        migrations.RunPython(verificar_y_convertir_virtual, revertir_virtual),
        migrations.AlterField(
            model_name='clasetaller',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
    ]