# Generated by Django 6.0.6 on 2026-09-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0003_alter_clasetaller_virtual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasetaller',
            name='virtual',
            field=models.BooleanField(db_column='virtual', default=False),
        ),
    ]
