# Generated by Django 6.0.6 on 2026-09-17 (E25 — rename Clasetaller → Encuentro)
# Hand-written following the E17/ADR-010 pattern: the autodetector does not
# detect the rename (db_column/db_table change simultaneously) and generates
# destructive AddField instead. RenameField only renames the Python field in
# state (db_column is preserved), so AlterField is required for the physical
# column rename; AlterModelTable is required for the physical table rename.

import django.db.models.deletion
from django.db import migrations, models


def _drop_fks_clasetaller(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT TABLE_NAME, CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE "
            "WHERE TABLE_SCHEMA = DATABASE() AND REFERENCED_TABLE_NAME = 'clasetaller'"
        )
        for table, name in cursor.fetchall():
            cursor.execute(f"ALTER TABLE `{table}` DROP FOREIGN KEY `{name}`")


def _restore_fks_clasetaller(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE `actividadrealizada` ADD CONSTRAINT `actividadrealizada_idclasetaller_fk` "
            "FOREIGN KEY (`idClaseTaller`) REFERENCES `clasetaller` (`idClaseTaller`)"
        )
        cursor.execute(
            "ALTER TABLE `asistenciataller` ADD CONSTRAINT `asistenciataller_idclasetaller_fk` "
            "FOREIGN KEY (`idClaseTaller`) REFERENCES `clasetaller` (`idClaseTaller`)"
        )
        cursor.execute(
            "ALTER TABLE `factorclase` ADD CONSTRAINT `factorclase_idclasetaller_fk` "
            "FOREIGN KEY (`idClaseTaller`) REFERENCES `clasetaller` (`idClaseTaller`)"
        )


def _restore_fks_encuentro(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE `actividadrealizada` ADD CONSTRAINT `actividadrealizada_idencuentro_fk` "
            "FOREIGN KEY (`idEncuentro`) REFERENCES `encuentro` (`idEncuentro`)"
        )
        cursor.execute(
            "ALTER TABLE `asistenciataller` ADD CONSTRAINT `asistenciataller_idencuentro_fk` "
            "FOREIGN KEY (`idEncuentro`) REFERENCES `encuentro` (`idEncuentro`)"
        )
        cursor.execute(
            "ALTER TABLE `factorclase` ADD CONSTRAINT `factorclase_idencuentro_fk` "
            "FOREIGN KEY (`idEncuentro`) REFERENCES `encuentro` (`idEncuentro`)"
        )


def _drop_fks_encuentro(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT TABLE_NAME, CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE "
            "WHERE TABLE_SCHEMA = DATABASE() AND REFERENCED_TABLE_NAME = 'encuentro'"
        )
        for table, name in cursor.fetchall():
            cursor.execute(f"ALTER TABLE `{table}` DROP FOREIGN KEY `{name}`")


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0004_alter_clasetaller_virtual'),
    ]

    operations = [
        migrations.RunPython(_drop_fks_clasetaller, _restore_fks_clasetaller),
        migrations.RenameModel(
            old_name='Clasetaller',
            new_name='Encuentro',
        ),
        migrations.RenameField(
            model_name='encuentro',
            old_name='idclasetaller',
            new_name='idencuentro',
        ),
        migrations.RenameField(
            model_name='actividadrealizada',
            old_name='idclasetaller',
            new_name='idencuentro',
        ),
        migrations.RenameField(
            model_name='asistenciataller',
            old_name='idclasetaller',
            new_name='idencuentro',
        ),
        migrations.RenameField(
            model_name='factorclase',
            old_name='idclasetaller',
            new_name='idencuentro',
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='idencuentro',
            field=models.AutoField(db_column='idEncuentro', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='actividadrealizada',
            name='idencuentro',
            field=models.ForeignKey(db_column='idEncuentro', on_delete=django.db.models.deletion.CASCADE, to='talleres.encuentro'),
        ),
        migrations.AlterField(
            model_name='asistenciataller',
            name='idencuentro',
            field=models.ForeignKey(blank=True, db_column='idEncuentro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='talleres.encuentro'),
        ),
        migrations.AlterField(
            model_name='factorclase',
            name='idencuentro',
            field=models.OneToOneField(db_column='idEncuentro', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='talleres.encuentro'),
        ),
        migrations.AlterModelTable(
            name='encuentro',
            table='encuentro',
        ),
        migrations.RunPython(_restore_fks_encuentro, _drop_fks_encuentro),
    ]