# Generated by Django 6.0.6 on 2026-10-02 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0005_rename_clasetaller_encuentro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadrealizada',
            name='idactividad',
            field=models.ForeignKey(db_column='idActividad', on_delete=django.db.models.deletion.DO_NOTHING, to='talleres.actividad'),
        ),
        migrations.AddField(
            model_name='actividadrealizada',
            name='idactividadrealizada',
            field=models.AutoField(db_column='idActividadRealizada', primary_key=True, serialize=False),
        ),
    ]
