# Generated by Django 6.0.6 on 2026-10-03 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0018_alter_departamento_options_alter_localidad_options_and_more'),
        ('talleres', '0006_actividadrealizada_idactividadrealizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='idtaller',
            field=models.ForeignKey(db_column='idTaller', on_delete=django.db.models.deletion.PROTECT, to='talleres.taller'),
        ),
        migrations.AlterField(
            model_name='actividadrealizada',
            name='idactividad',
            field=models.ForeignKey(db_column='idActividad', on_delete=django.db.models.deletion.PROTECT, to='talleres.actividad'),
        ),
        migrations.AlterField(
            model_name='asistenciataller',
            name='idcomportamiento',
            field=models.ForeignKey(blank=True, db_column='idComportamiento', null=True, on_delete=django.db.models.deletion.PROTECT, to='talleres.comportamiento'),
        ),
        migrations.AlterField(
            model_name='asistenciataller',
            name='idpersonaep',
            field=models.ForeignKey(blank=True, db_column='idPersonaEP', null=True, on_delete=django.db.models.deletion.PROTECT, to='personas.personaep'),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='idtaller',
            field=models.ForeignKey(db_column='idTaller', on_delete=django.db.models.deletion.PROTECT, to='talleres.taller'),
        ),
        migrations.AlterField(
            model_name='factorclase',
            name='idfactorglobal',
            field=models.ForeignKey(db_column='idFactorGlobal', on_delete=django.db.models.deletion.PROTECT, to='talleres.factorglobal'),
        ),
        migrations.AlterField(
            model_name='valorvariableuo',
            name='idvariableuo',
            field=models.ForeignKey(db_column='idVariableUO', on_delete=django.db.models.deletion.PROTECT, to='talleres.variableuo'),
        ),
        migrations.AlterField(
            model_name='variableuo',
            name='idcomportamiento',
            field=models.ForeignKey(db_column='idComportamiento', on_delete=django.db.models.deletion.PROTECT, to='talleres.comportamiento'),
        ),
        migrations.AlterField(
            model_name='variableuo',
            name='idunidadobservacion',
            field=models.ForeignKey(db_column='idUnidadObservacion', on_delete=django.db.models.deletion.PROTECT, to='talleres.unidadobservacion'),
        ),
    ]
