# Generated by Django 6.0.6 on 2026-10-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0007_alter_actividad_idtaller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistenciataller',
            name='idcomportamiento',
        ),
        migrations.RemoveField(
            model_name='variableuo',
            name='idcomportamiento',
        ),
        migrations.DeleteModel(
            name='Comportamiento',
        ),
    ]
