# Generated by Django 6.0.6 on 2026-10-03 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0008_remove_asistenciataller_idcomportamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorclase',
            name='idencuentro',
            field=models.ForeignKey(db_column='idEncuentro', on_delete=django.db.models.deletion.CASCADE, to='talleres.encuentro'),
        ),
        migrations.AddField(
            model_name='factorclase',
            name='idfactorclase',
            field=models.AutoField(db_column='idFactorClase', primary_key=True, serialize=False),
        ),
    ]
