# Generated by Django 6.0.6 on 2026-10-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0009_factorclase_swap_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorvariableuo',
            name='idasistenciataller',
            field=models.ForeignKey(blank=True, db_column='idAsistenciaTaller', null=True, on_delete=django.db.models.deletion.CASCADE, to='talleres.asistenciataller'),
        ),
    ]
