# Generated by Django 6.0.6 on 2026-10-04 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0010_valorvariableuo_idasistenciataller'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorvariableuo',
            name='idactividadrealizada',
            field=models.ForeignKey(blank=True, db_column='idActividadRealizada', null=True, on_delete=django.db.models.deletion.CASCADE, to='talleres.actividadrealizada'),
        ),
    ]
