# Generated by Django 6.0.6 (E33 — rename Factorclase -> EncuentroFactorGlobal
# y Actividadrealizada -> EncuentroActividad, incluida la FK Valorvariableuo)
# Renombra modelos, tablas, PKs y columnas fisicas preservando filas, PKs y FKs.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0011_valorvariableuo_idactividadrealizada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Factorclase',
            new_name='EncuentroFactorGlobal',
        ),
        migrations.RenameField(
            model_name='encuentrofactorglobal',
            old_name='idfactorclase',
            new_name='idencuentrofactorglobal',
        ),
        migrations.AlterField(
            model_name='encuentrofactorglobal',
            name='idencuentrofactorglobal',
            field=models.AutoField(db_column='idEncuentroFactorGlobal', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='encuentrofactorglobal',
            table='encuentrofactorglobal',
        ),
        migrations.RenameModel(
            old_name='Actividadrealizada',
            new_name='EncuentroActividad',
        ),
        migrations.RenameField(
            model_name='encuentroactividad',
            old_name='idactividadrealizada',
            new_name='idencuentroactividad',
        ),
        migrations.AlterField(
            model_name='encuentroactividad',
            name='idencuentroactividad',
            field=models.AutoField(db_column='idEncuentroActividad', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='encuentroactividad',
            table='encuentroactividad',
        ),
        migrations.RenameField(
            model_name='valorvariableuo',
            old_name='idactividadrealizada',
            new_name='idencuentroactividad',
        ),
        migrations.AlterField(
            model_name='valorvariableuo',
            name='idencuentroactividad',
            field=models.ForeignKey(blank=True, db_column='idEncuentroActividad', null=True, on_delete=django.db.models.deletion.CASCADE, to='talleres.encuentroactividad'),
        ),
    ]
