# Generated by Django 6.0.6 on 2026-10-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0020_alter_departamento_id_departamento_and_more'),
        ('talleres', '0013_rename_idactividad_actividad_id_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='id_actividad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talleres.taller'),
        ),
        migrations.AlterField(
            model_name='asistenciataller',
            name='encuentro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talleres.encuentro'),
        ),
        migrations.AlterField(
            model_name='asistenciataller',
            name='id_asistencia_taller',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asistenciataller',
            name='persona_ep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personas.personaep'),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='id_encuentro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talleres.taller'),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='encuentroactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talleres.actividad'),
        ),
        migrations.AlterField(
            model_name='encuentroactividad',
            name='encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.encuentro'),
        ),
        migrations.AlterField(
            model_name='encuentroactividad',
            name='id_encuentro_actividad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encuentrofactorglobal',
            name='encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.encuentro'),
        ),
        migrations.AlterField(
            model_name='encuentrofactorglobal',
            name='factor_global',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talleres.factorglobal'),
        ),
        migrations.AlterField(
            model_name='encuentrofactorglobal',
            name='id_encuentro_factor_global',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factorglobal',
            name='id_factor_global',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taller',
            name='id_taller',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taller',
            name='tipo_taller',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='unidadobservacion',
            name='id_unidad_observacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='valorvariableuo',
            name='asistencia_taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talleres.asistenciataller'),
        ),
        migrations.AlterField(
            model_name='valorvariableuo',
            name='encuentro_actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talleres.encuentroactividad'),
        ),
        migrations.AlterField(
            model_name='valorvariableuo',
            name='id_valor_variable_uo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='valorvariableuo',
            name='variable_uo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talleres.variableuo'),
        ),
        migrations.AlterField(
            model_name='variableuo',
            name='id_variable_uo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variableuo',
            name='unidad_observacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talleres.unidadobservacion'),
        ),
    ]
