# Generated by Django 6.0.6 on 2026-07-04 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obrasocial',
            fields=[
                ('idobrasocial', models.AutoField(db_column='idObraSocial', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('esestatal', models.IntegerField(blank=True, db_column='esEstatal', null=True)),
            ],
            options={
                'db_table': 'obrasocial',
            },
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('idos', models.AutoField(db_column='idOS', primary_key=True, serialize=False)),
                ('borrado', models.IntegerField(db_column='borrado')),
                ('idobrasocial', models.ForeignKey(db_column='idObraSocial', on_delete=django.db.models.deletion.DO_NOTHING, to='obra_social.obrasocial')),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.personaep')),
            ],
            options={
                'db_table': 'os',
            },
        ),
    ]
