# Generated by Django 6.0.6 on 2026-09-03 15:42

from django.db import migrations, models


def verificar_y_convertir_borrado(apps, schema_editor):
    Os = apps.get_model('obra_social', 'Os')
    valores = set(v['borrado'] for v in Os.objects.values('borrado').distinct())
    if not valores.issubset({0, 1}):
        raise RuntimeError(
            f"Valores inesperados en obra_social.Os.borrado: {sorted(valores)}. "
            "Se esperaban únicamente 0 y 1; migración abortada sin cambios."
        )
    Os.objects.filter(borrado=0).update(borrado=False)
    Os.objects.exclude(borrado=0).update(borrado=True)


def revertir_borrado(apps, schema_editor):
    Os = apps.get_model('obra_social', 'Os')
    Os.objects.filter(borrado=False).update(borrado=0)
    Os.objects.exclude(borrado=False).update(borrado=1)


class Migration(migrations.Migration):

    dependencies = [
        ('obra_social', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(verificar_y_convertir_borrado, revertir_borrado),
        migrations.AlterField(
            model_name='os',
            name='borrado',
            field=models.BooleanField(db_column='borrado', default=False),
        ),
    ]
