# Generated by Django 6.0.6 on 2026-09-03 23:31

from django.db import migrations, models


def verificar_y_convertir_esestatal(apps, schema_editor):
    Obrasocial = apps.get_model('obra_social', 'Obrasocial')
    valores = set(v['esestatal'] for v in Obrasocial.objects.values('esestatal').distinct())
    if not valores.issubset({0, 1}):
        raise RuntimeError(
            f"Valores inesperados en obra_social.Obrasocial.esestatal: {sorted(valores)}. "
            "Se esperaban únicamente 0 y 1; migración abortada sin cambios."
        )
    Obrasocial.objects.filter(esestatal=0).update(esestatal=False)
    Obrasocial.objects.exclude(esestatal=0).update(esestatal=True)


def revertir_esestatal(apps, schema_editor):
    Obrasocial = apps.get_model('obra_social', 'Obrasocial')
    Obrasocial.objects.filter(esestatal=False).update(esestatal=0)
    Obrasocial.objects.exclude(esestatal=False).update(esestatal=1)


class Migration(migrations.Migration):

    dependencies = [
        ('obra_social', '0002_alter_os_borrado'),
    ]

    operations = [
        migrations.RunPython(verificar_y_convertir_esestatal, revertir_esestatal),
        migrations.AlterField(
            model_name='obrasocial',
            name='esestatal',
            field=models.BooleanField(db_column='esEstatal', default=False),
        ),
    ]