# Generated by Django 6.0.6 (E33 — rename Os -> Cobertura)
# Renombra modelo, tabla, PK y columna fisica preservando filas, PKs y FKs.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra_social', '0003_alter_obrasocial_esestatal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Os',
            new_name='Cobertura',
        ),
        migrations.RenameField(
            model_name='cobertura',
            old_name='idos',
            new_name='idcobertura',
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='idcobertura',
            field=models.AutoField(db_column='idCobertura', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='cobertura',
            table='cobertura',
        ),
    ]
