# Generated by Django 6.0.6 on 2026-10-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obra_social', '0004_rename_os_cobertura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobertura',
            old_name='idcobertura',
            new_name='id_cobertura',
        ),
        migrations.RenameField(
            model_name='cobertura',
            old_name='idobrasocial',
            new_name='obra_social',
        ),
        migrations.RenameField(
            model_name='cobertura',
            old_name='idpersonaep',
            new_name='persona_ep',
        ),
        migrations.RenameField(
            model_name='obrasocial',
            old_name='esestatal',
            new_name='es_estatal',
        ),
        migrations.RenameField(
            model_name='obrasocial',
            old_name='idobrasocial',
            new_name='id_obra_social',
        ),
        migrations.AlterModelTable(
            name='cobertura',
            table='obra_social_cobertura',
        ),
        migrations.AlterModelTable(
            name='obrasocial',
            table='obra_social_obra_social',
        ),
    ]
