# Generated by Django 6.0.6 on 2026-10-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra_social', '0005_rename_idcobertura_cobertura_id_cobertura_and_more'),
        ('personas', '0020_alter_departamento_id_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobertura',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='id_cobertura',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='obra_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='obra_social.obrasocial'),
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='persona_ep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personas.personaep'),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='es_estatal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='id_obra_social',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
