# Generated by Django 6.0.6 on 2026-07-04 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('idenfermedad', models.AutoField(db_column='idEnfermedad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'enfermedad',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('idmedicamento', models.AutoField(db_column='idMedicamento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('esantiparkinsoniano', models.IntegerField(blank=True, db_column='esAntiparkinsoniano', null=True)),
                ('eslevodopa', models.IntegerField(blank=True, db_column='esLevodopa', null=True)),
            ],
            options={
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('iddiagnostico', models.AutoField(db_column='idDiagnostico', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('borrado', models.IntegerField(db_column='borrado')),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.personaep')),
                ('idenfermedad', models.ForeignKey(db_column='idEnfermedad', on_delete=django.db.models.deletion.DO_NOTHING, to='salud.enfermedad')),
            ],
            options={
                'db_table': 'diagnostico',
            },
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('idevolucion', models.AutoField(db_column='idEvolucion', primary_key=True, serialize=False)),
                ('escalaevolucion', models.IntegerField(db_column='escalaEvolucion')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('borrado', models.IntegerField(db_column='borrado')),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.personaep')),
            ],
            options={
                'db_table': 'evolucion',
            },
        ),
        migrations.CreateModel(
            name='Indicacionmedicamento',
            fields=[
                ('idindicacion', models.AutoField(db_column='idIndicacion', primary_key=True, serialize=False)),
                ('cantidadmiligramos', models.IntegerField(blank=True, db_column='cantidadMiligramos', null=True)),
                ('estavigente', models.IntegerField(blank=True, db_column='estaVigente', null=True)),
                ('fechaprescripcion', models.DateField(blank=True, db_column='fechaPrescripcion', null=True)),
                ('horadetoma', models.TimeField(blank=True, db_column='horaDeToma', null=True)),
                ('borrado', models.IntegerField(db_column='borrado')),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.personaep')),
                ('idmedicamento', models.ForeignKey(db_column='idMedicamento', on_delete=django.db.models.deletion.DO_NOTHING, to='salud.medicamento')),
            ],
            options={
                'db_table': 'indicacionmedicamento',
            },
        ),
    ]
