# Generated by Django 6.0.6 on 2026-09-03 23:31

from django.db import migrations, models

CAMPOS = (
    ('Indicacionmedicamento', 'estavigente'),
    ('Medicamento', 'esantiparkinsoniano'),
    ('Medicamento', 'eslevodopa'),
)


def verificar_y_convertir_campos(apps, schema_editor):
    for model_name, campo in CAMPOS:
        Modelo = apps.get_model('salud', model_name)
        valores = set(v[campo] for v in Modelo.objects.values(campo).distinct())
        if not valores.issubset({0, 1}):
            raise RuntimeError(
                f"Valores inesperados en salud.{model_name}.{campo}: {sorted(valores)}. "
                "Se esperaban únicamente 0 y 1; migración abortada sin cambios."
            )
        Modelo.objects.filter(**{campo: 0}).update(**{campo: False})
        Modelo.objects.exclude(**{campo: 0}).update(**{campo: True})


def revertir_campos(apps, schema_editor):
    for model_name, campo in CAMPOS:
        Modelo = apps.get_model('salud', model_name)
        Modelo.objects.filter(**{campo: False}).update(**{campo: 0})
        Modelo.objects.exclude(**{campo: False}).update(**{campo: 1})


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0002_alter_diagnostico_borrado_alter_evolucion_borrado_and_more'),
    ]

    operations = [
        migrations.RunPython(verificar_y_convertir_campos, revertir_campos),
        migrations.AlterField(
            model_name='indicacionmedicamento',
            name='estavigente',
            field=models.BooleanField(db_column='estaVigente', default=False),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='esantiparkinsoniano',
            field=models.BooleanField(db_column='esAntiparkinsoniano', default=False),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='eslevodopa',
            field=models.BooleanField(db_column='esLevodopa', default=False),
        ),
    ]