# Generated by Django 6.0.6 on 2026-10-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0003_alter_indicacionmedicamento_estavigente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostico',
            old_name='idenfermedad',
            new_name='enfermedad',
        ),
        migrations.RenameField(
            model_name='diagnostico',
            old_name='iddiagnostico',
            new_name='id_diagnostico',
        ),
        migrations.RenameField(
            model_name='diagnostico',
            old_name='idpersonaep',
            new_name='persona_ep',
        ),
        migrations.RenameField(
            model_name='enfermedad',
            old_name='idenfermedad',
            new_name='id_enfermedad',
        ),
        migrations.RenameField(
            model_name='evolucion',
            old_name='escalaevolucion',
            new_name='escala_evolucion',
        ),
        migrations.RenameField(
            model_name='evolucion',
            old_name='idevolucion',
            new_name='id_evolucion',
        ),
        migrations.RenameField(
            model_name='evolucion',
            old_name='idpersonaep',
            new_name='persona_ep',
        ),
        migrations.RenameField(
            model_name='indicacionmedicamento',
            old_name='cantidadmiligramos',
            new_name='cantidad_miligramos',
        ),
        migrations.RenameField(
            model_name='indicacionmedicamento',
            old_name='estavigente',
            new_name='esta_vigente',
        ),
        migrations.RenameField(
            model_name='indicacionmedicamento',
            old_name='fechaprescripcion',
            new_name='fecha_prescripcion',
        ),
        migrations.RenameField(
            model_name='indicacionmedicamento',
            old_name='horadetoma',
            new_name='hora_de_toma',
        ),
        migrations.RenameField(
            model_name='indicacionmedicamento',
            old_name='idindicacion',
            new_name='id_indicacion',
        ),
        migrations.RenameField(
            model_name='indicacionmedicamento',
            old_name='idmedicamento',
            new_name='medicamento',
        ),
        migrations.RenameField(
            model_name='indicacionmedicamento',
            old_name='idpersonaep',
            new_name='persona_ep',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='esantiparkinsoniano',
            new_name='es_antiparkinsoniano',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='eslevodopa',
            new_name='es_levodopa',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='idmedicamento',
            new_name='id_medicamento',
        ),
        migrations.AlterModelTable(
            name='diagnostico',
            table='salud_diagnostico',
        ),
        migrations.AlterModelTable(
            name='enfermedad',
            table='salud_enfermedad',
        ),
        migrations.AlterModelTable(
            name='evolucion',
            table='salud_evolucion',
        ),
        migrations.AlterModelTable(
            name='indicacionmedicamento',
            table='salud_indicacion_medicamento',
        ),
        migrations.AlterModelTable(
            name='medicamento',
            table='salud_medicamento',
        ),
    ]
