# Generated by Django 6.0.6 on 2026-10-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0020_alter_departamento_id_departamento_and_more'),
        ('salud', '0004_rename_idenfermedad_diagnostico_enfermedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='enfermedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salud.enfermedad'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='id_diagnostico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='persona_ep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personas.personaep'),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='id_enfermedad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='escala_evolucion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='id_evolucion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='persona_ep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personas.personaep'),
        ),
        migrations.AlterField(
            model_name='indicacionmedicamento',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indicacionmedicamento',
            name='cantidad_miligramos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicacionmedicamento',
            name='esta_vigente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indicacionmedicamento',
            name='fecha_prescripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicacionmedicamento',
            name='hora_de_toma',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicacionmedicamento',
            name='id_indicacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indicacionmedicamento',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salud.medicamento'),
        ),
        migrations.AlterField(
            model_name='indicacionmedicamento',
            name='persona_ep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personas.personaep'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='es_antiparkinsoniano',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='es_levodopa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='id_medicamento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
