# Generated by Django 3.2.5 on 2021-08-02 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(db_column='idDireccion', primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, max_length=45, null=True)),
                ('departamento', models.CharField(blank=True, max_length=45, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Direccion',
            },
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('idEnfermedad', models.IntegerField(db_column='idEnfermedad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Enfermedad',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('idMedicamento', models.AutoField(db_column='idMedicamento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('esAntiparkinsoniano', models.BooleanField(db_column='esAntiparkinsoniano')),
                ('esLevodopa', models.BooleanField(db_column='esLevodopa')),
            ],
            options={
                'db_table': 'Medicamento',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idMunicipio', models.AutoField(db_column='idMunicipio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('provincia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1)),
                ('telefono', models.IntegerField()),
                ('idDireccion', models.ForeignKey(blank=True, db_column='idDireccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.direccion')),
            ],
            options={
                'db_table': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('idTipoEvento', models.AutoField(db_column='idTipoEvento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'TipoEvento',
            },
        ),
        migrations.CreateModel(
            name='PersonaEP',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='teleparkApi.persona')),
                ('idPersonaEP', models.AutoField(db_column='idPersonaEP', primary_key=True, serialize=False)),
                ('escolaridadCompleta', models.BooleanField(default=False)),
                ('fechaNacimiento', models.DateField()),
                ('maximaEscolaridadAlcanzada', models.CharField(choices=[('SIN_ESCOLARIDAD', 'Sin Escolaridad'), ('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario'), ('TERCIARIO', 'Terciario'), ('UNIVERSITARIO', 'Universitario')], default='SIN_ESCOLARIDAD', max_length=16)),
                ('tieneAcompaniante', models.BooleanField(default=False)),
                ('tieneCuidador', models.BooleanField(default=False)),
                ('viveSolo', models.BooleanField(default=False)),
                ('idReferente', models.ForeignKey(db_column='idReferente', on_delete=django.db.models.deletion.PROTECT, related_name='personaEpReferente', to='teleparkApi.persona')),
            ],
            options={
                'db_table': 'PersonaEP',
            },
            bases=('teleparkApi.persona',),
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('idLocalidad', models.AutoField(db_column='idLocalidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('codigoPostal', models.IntegerField()),
                ('idMunicipio', models.ForeignKey(blank=True, db_column='idMunicipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.municipio')),
            ],
            options={
                'db_table': 'Localidad',
            },
        ),
        migrations.AddField(
            model_name='direccion',
            name='idLocalidad',
            field=models.ForeignKey(blank=True, db_column='idLocalidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.localidad'),
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('idObraSocial', models.AutoField(db_column='idObraSocial', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('esEstatal', models.BooleanField(db_column='esEstatal')),
                ('idPersonaEP', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.personaep')),
            ],
            options={
                'db_table': 'ObraSocial',
            },
        ),
        migrations.CreateModel(
            name='IndicacionMedicamento',
            fields=[
                ('idIndicacion', models.AutoField(db_column='idIndicacion', primary_key=True, serialize=False)),
                ('cantidadMiligramos', models.IntegerField()),
                ('estaVigente', models.BooleanField(null=True)),
                ('fechaPrescripcion', models.DateField()),
                ('horaDeToma', models.TimeField()),
                ('idMedicamento', models.ForeignKey(db_column='idMedicamento', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.medicamento')),
                ('idPersonaEP', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.personaep')),
            ],
            options={
                'db_table': 'IndicacionMedicamento',
            },
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('idEvolucion', models.AutoField(db_column='idEvolucion', primary_key=True, serialize=False)),
                ('escalaEvolucion', models.BooleanField(db_column='escalaEvolucion')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('idPersona', models.ForeignKey(db_column='idPersona', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.personaep')),
            ],
            options={
                'db_table': 'Evolucion',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=100)),
                ('idPersonaEP', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.PROTECT, related_name='eventoPersonaEP', to='teleparkApi.personaep')),
            ],
            options={
                'db_table': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('idDiagnostico', models.AutoField(db_column='idDiagnostico', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('idEnfermedad', models.ForeignKey(db_column='idEnfermedad', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.enfermedad')),
                ('idPersona', models.ForeignKey(db_column='idPersona', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.personaep')),
            ],
            options={
                'db_table': 'Diagnostico',
            },
        ),
        migrations.CreateModel(
            name='TipoParentesco',
            fields=[
                ('idTipoParentesco', models.AutoField(db_column='idTipoParentesco', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('idPersona', models.OneToOneField(db_column='idPersona', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipoParentescoPersona', to='teleparkApi.persona')),
                ('idPersonaEP', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipoParentescoPersonaEP', to='teleparkApi.personaep')),
            ],
            options={
                'db_table': 'TipoParentesco',
                'unique_together': {('idPersona', 'idPersonaEP')},
            },
        ),
    ]
