# Generated by Django 6.0.6 on 2026-07-03 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comportamiento',
            fields=[
                ('idcomportamiento', models.AutoField(db_column='idComportamiento', primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'comportamiento',
            },
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('idenfermedad', models.AutoField(db_column='idEnfermedad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'enfermedad',
            },
        ),
        migrations.CreateModel(
            name='Factorglobal',
            fields=[
                ('idfactorglobal', models.AutoField(db_column='idFactorGlobal', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'factorglobal',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('idlocalidad', models.AutoField(db_column='idLocalidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('codigopostal', models.IntegerField(db_column='codigoPostal')),
            ],
            options={
                'db_table': 'localidad',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('idmedicamento', models.AutoField(db_column='idMedicamento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('esantiparkinsoniano', models.IntegerField(blank=True, db_column='esAntiparkinsoniano', null=True)),
                ('eslevodopa', models.IntegerField(blank=True, db_column='esLevodopa', null=True)),
            ],
            options={
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idmunicipio', models.AutoField(db_column='idMunicipio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('provincia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Obrasocial',
            fields=[
                ('idobrasocial', models.AutoField(db_column='idObraSocial', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('esestatal', models.IntegerField(blank=True, db_column='esEstatal', null=True)),
            ],
            options={
                'db_table': 'obrasocial',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('idtaller', models.AutoField(db_column='idTaller', primary_key=True, serialize=False)),
                ('tipotaller', models.CharField(db_column='tipoTaller', max_length=45)),
            ],
            options={
                'db_table': 'taller',
            },
        ),
        migrations.CreateModel(
            name='Tipoevento',
            fields=[
                ('idtipoevento', models.AutoField(db_column='idTipoEvento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('desactivataller', models.IntegerField(blank=True, db_column='desactivaTaller', null=True)),
                ('borrado', models.IntegerField(db_column='borrado')),
            ],
            options={
                'db_table': 'tipoevento',
            },
        ),
        migrations.CreateModel(
            name='Unidadobservacion',
            fields=[
                ('idunidadobservacion', models.AutoField(db_column='idUnidadObservacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'unidadobservacion',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('iddireccion', models.AutoField(db_column='idDireccion', primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, max_length=45, null=True)),
                ('departamento', models.CharField(blank=True, max_length=45, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('idlocalidad', models.ForeignKey(blank=True, db_column='idLocalidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.localidad')),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='idmunicipio',
            field=models.ForeignKey(blank=True, db_column='idMunicipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.municipio'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=35)),
                ('borrado', models.IntegerField(db_column='borrado')),
                ('espaciente', models.IntegerField(db_column='esPaciente')),
                ('iddireccion', models.ForeignKey(blank=True, db_column='idDireccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.direccion')),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Clasetaller',
            fields=[
                ('idclasetaller', models.AutoField(db_column='idClaseTaller', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('virtual', models.IntegerField()),
                ('idtaller', models.ForeignKey(db_column='idTaller', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.taller')),
            ],
            options={
                'db_table': 'clasetaller',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idactividad', models.AutoField(db_column='idActividad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('idtaller', models.ForeignKey(db_column='idTaller', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.taller')),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Variableuo',
            fields=[
                ('idvariableuo', models.AutoField(db_column='idVariableUO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('idcomportamiento', models.ForeignKey(db_column='idComportamiento', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.comportamiento')),
                ('idunidadobservacion', models.ForeignKey(db_column='idUnidadObservacion', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.unidadobservacion')),
            ],
            options={
                'db_table': 'variableuo',
            },
        ),
        migrations.CreateModel(
            name='Valorvariableuo',
            fields=[
                ('idvalorvariableuo', models.AutoField(db_column='idValorVariableUO', primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=45)),
                ('idvariableuo', models.ForeignKey(db_column='idVariableUO', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.variableuo')),
            ],
            options={
                'db_table': 'valorvariableuo',
            },
        ),
        migrations.CreateModel(
            name='PersonaEp',
            fields=[
                ('activataller', models.IntegerField(blank=True, db_column='activaTaller', null=True)),
                ('escolaridadcompleta', models.IntegerField(blank=True, db_column='escolaridadCompleta', null=True)),
                ('fechainicio', models.DateTimeField(db_column='fechaInicio')),
                ('fechanacimiento', models.DateField(db_column='fechaNacimiento')),
                ('maximaescolaridadalcanzada', models.CharField(blank=True, db_column='maximaEscolaridadAlcanzada', max_length=45, null=True)),
                ('sexo', models.CharField(max_length=45)),
                ('tieneacompanante', models.IntegerField(db_column='tieneAcompanante')),
                ('tienecuidador', models.IntegerField(db_column='tieneCuidador')),
                ('vivesolo', models.IntegerField(db_column='viveSolo')),
                ('ocupacionprevia', models.CharField(db_column='ocupacionPrevia', max_length=45)),
                ('ocupacionactual', models.CharField(db_column='ocupacionActual', max_length=45)),
                ('idpersona', models.OneToOneField(db_column='idPersona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='teleparkApi.persona')),
                ('idreferente', models.ForeignKey(db_column='idReferente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='teleparkApi.persona')),
            ],
            options={
                'db_table': 'persona_ep',
                'unique_together': {('idpersona', 'idreferente')},
            },
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('idos', models.AutoField(db_column='idOS', primary_key=True, serialize=False)),
                ('borrado', models.IntegerField(db_column='borrado')),
                ('idobrasocial', models.ForeignKey(db_column='idObraSocial', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.obrasocial')),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.personaep')),
            ],
            options={
                'db_table': 'os',
            },
        ),
        migrations.CreateModel(
            name='Indicacionmedicamento',
            fields=[
                ('idindicacion', models.AutoField(db_column='idIndicacion', primary_key=True, serialize=False)),
                ('cantidadmiligramos', models.IntegerField(blank=True, db_column='cantidadMiligramos', null=True)),
                ('estavigente', models.IntegerField(blank=True, db_column='estaVigente', null=True)),
                ('fechaprescripcion', models.DateField(blank=True, db_column='fechaPrescripcion', null=True)),
                ('horadetoma', models.TimeField(blank=True, db_column='horaDeToma', null=True)),
                ('borrado', models.IntegerField(db_column='borrado')),
                ('idmedicamento', models.ForeignKey(db_column='idMedicamento', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.medicamento')),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.personaep')),
            ],
            options={
                'db_table': 'indicacionmedicamento',
            },
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('idevolucion', models.AutoField(db_column='idEvolucion', primary_key=True, serialize=False)),
                ('escalaevolucion', models.IntegerField(db_column='escalaEvolucion')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('borrado', models.IntegerField(db_column='borrado')),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.personaep')),
            ],
            options={
                'db_table': 'evolucion',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idevento', models.AutoField(db_column='idEvento', primary_key=True, serialize=False)),
                ('fechadesde', models.DateField(blank=True, db_column='fechaDesde', null=True)),
                ('fechahasta', models.DateField(blank=True, db_column='fechaHasta', null=True)),
                ('motivo', models.CharField(blank=True, max_length=256, null=True)),
                ('borrado', models.IntegerField(db_column='borrado')),
                ('idtipoevento', models.ForeignKey(db_column='idTipoEvento', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.tipoevento')),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.personaep')),
            ],
            options={
                'db_table': 'evento',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('iddiagnostico', models.AutoField(db_column='idDiagnostico', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('borrado', models.IntegerField(db_column='borrado')),
                ('idenfermedad', models.ForeignKey(db_column='idEnfermedad', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.enfermedad')),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.personaep')),
            ],
            options={
                'db_table': 'diagnostico',
            },
        ),
        migrations.CreateModel(
            name='Asistenciataller',
            fields=[
                ('idasistenciataller', models.AutoField(db_column='idAsistenciaTaller', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=45)),
                ('idclasetaller', models.ForeignKey(db_column='idClaseTaller', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.clasetaller')),
                ('idcomportamiento', models.ForeignKey(blank=True, db_column='idComportamiento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.comportamiento')),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.personaep')),
            ],
            options={
                'db_table': 'asistenciataller',
            },
        ),
        migrations.CreateModel(
            name='Actividadrealizada',
            fields=[
                ('idactividad', models.OneToOneField(db_column='idActividad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='teleparkApi.actividad')),
                ('idclasetaller', models.ForeignKey(db_column='idClaseTaller', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.clasetaller')),
            ],
            options={
                'db_table': 'actividadrealizada',
                'unique_together': {('idactividad', 'idclasetaller')},
            },
        ),
        migrations.CreateModel(
            name='Factorclase',
            fields=[
                ('idclasetaller', models.OneToOneField(db_column='idClaseTaller', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='teleparkApi.clasetaller')),
                ('idfactorglobal', models.ForeignKey(db_column='idFactorGlobal', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.factorglobal')),
            ],
            options={
                'db_table': 'factorclase',
                'unique_together': {('idclasetaller', 'idfactorglobal')},
            },
        ),
        migrations.CreateModel(
            name='Tipoparentesco',
            fields=[
                ('idpersona', models.OneToOneField(db_column='idPersona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='teleparkApi.persona')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='teleparkApi.personaep')),
            ],
            options={
                'db_table': 'tipoparentesco',
                'unique_together': {('idpersona', 'idpersonaep')},
            },
        ),
    ]
