# Generated by Django 3.2.6 on 2021-08-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('iddiagnostico', models.AutoField(db_column='idDiagnostico', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'diagnostico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('iddireccion', models.AutoField(db_column='idDireccion', primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, max_length=45, null=True)),
                ('departamento', models.CharField(blank=True, max_length=45, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('idenfermedad', models.IntegerField(db_column='idEnfermedad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'enfermedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idevento', models.AutoField(db_column='idEvento', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('idevolucion', models.AutoField(db_column='idEvolucion', primary_key=True, serialize=False)),
                ('escalaevolucion', models.IntegerField(db_column='escalaEvolucion')),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evolucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicacionmedicamento',
            fields=[
                ('idindicacion', models.AutoField(db_column='idIndicacion', primary_key=True, serialize=False)),
                ('cantidadmiligramos', models.IntegerField(blank=True, db_column='cantidadMiligramos', null=True)),
                ('estavigente', models.IntegerField(blank=True, db_column='estaVigente', null=True)),
                ('fechaprescripcion', models.DateField(blank=True, db_column='fechaPrescripcion', null=True)),
                ('horadetoma', models.TimeField(blank=True, db_column='horaDeToma', null=True)),
            ],
            options={
                'db_table': 'indicacionmedicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('idlocalidad', models.AutoField(db_column='idLocalidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('codigopostal', models.IntegerField(db_column='codigoPostal')),
            ],
            options={
                'db_table': 'localidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('idmedicamento', models.AutoField(db_column='idMedicamento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('esantiparkinsoniano', models.IntegerField(db_column='esAntiparkinsoniano')),
                ('eslevodopa', models.IntegerField(db_column='esLevodopa')),
            ],
            options={
                'db_table': 'medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idmunicipio', models.AutoField(db_column='idMunicipio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('provincia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obrasocial',
            fields=[
                ('idobrasocial', models.IntegerField(db_column='idObraSocial', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('esestatal', models.IntegerField(db_column='esEstatal')),
            ],
            options={
                'db_table': 'obrasocial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoevento',
            fields=[
                ('idtipoevento', models.AutoField(db_column='idTipoEvento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipoevento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonaEp',
            fields=[
                ('escolaridadcompleta', models.IntegerField(blank=True, db_column='escolaridadCompleta', null=True)),
                ('fechainicio', models.DateTimeField(db_column='fechaInicio')),
                ('fechanacimiento', models.DateField(db_column='fechaNacimiento')),
                ('maximaescolaridadalcanzada', models.CharField(blank=True, db_column='maximaEscolaridadAlcanzada', max_length=45, null=True)),
                ('sexo', models.CharField(max_length=45)),
                ('tieneacompanante', models.IntegerField(db_column='tieneAcompanante')),
                ('tienecuidador', models.IntegerField(db_column='tieneCuidador')),
                ('vivesolo', models.IntegerField(db_column='viveSolo')),
                ('ocupacionprevia', models.CharField(db_column='ocupacionPrevia', max_length=45)),
                ('ocupacionactual', models.CharField(db_column='ocupacionActual', max_length=45)),
                ('persona_idpersona', models.OneToOneField(db_column='Persona_idPersona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='teleparkApi.persona')),
            ],
            options={
                'db_table': 'persona_ep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoparentesco',
            fields=[
                ('persona_idpersona', models.OneToOneField(db_column='Persona_idPersona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='teleparkApi.persona')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipoparentesco',
                'managed': False,
            },
        ),
    ]
