-- MySQL Script generated by MySQL Workbench
-- Thu Jun 25 13:32:21 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pruebatelepark
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pruebatelepark
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pruebatelepark` DEFAULT CHARACTER SET utf8 ;
USE `pruebatelepark` ;

-- -----------------------------------------------------
-- Table `pruebatelepark`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`Municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMunicipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`Localidad` (
  `idLocalidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `codigoPostal` INT NOT NULL,
  `idMunicipio` INT NULL,
  PRIMARY KEY (`idLocalidad`),
  INDEX `fk_Localidad_Municipio1_idx` (`idMunicipio` ASC) VISIBLE,
  CONSTRAINT `fk_Localidad_Municipio1`
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `pruebatelepark`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  `numero` INT NULL,
  `piso` INT NULL,
  `idLocalidad` INT NULL,
  PRIMARY KEY (`idDireccion`),
  INDEX `fk_Direccion_Localidad1_idx` (`idLocalidad` ASC) VISIBLE,
  CONSTRAINT `fk_Direccion_Localidad1`
    FOREIGN KEY (`idLocalidad`)
    REFERENCES `pruebatelepark`.`Localidad` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(35) NOT NULL,
  `idDireccion` INT NULL,
  `borrado` TINYINT NULL,
  `esPaciente` TINYINT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_Persona_Direccion1_idx` (`idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Direccion1`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `pruebatelepark`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`Persona_EP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`Persona_EP` (
  `activaTaller` TINYINT NULL,
  `escolaridadCompleta` TINYINT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `maximaEscolaridadAlcanzada` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `tieneAcompanante` TINYINT NOT NULL,
  `tieneCuidador` TINYINT NOT NULL,
  `viveSolo` TINYINT NOT NULL,
  `ocupacionPrevia` VARCHAR(45) NOT NULL,
  `ocupacionActual` VARCHAR(45) NOT NULL,
  `idPersona` INT NOT NULL,
  `idReferente` INT NOT NULL,
  PRIMARY KEY (`idPersona`, `idReferente`),
  INDEX `fk_Persona_EP_Persona1_idx` (`idReferente` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_EP_Persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `pruebatelepark`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_EP_Persona1`
    FOREIGN KEY (`idReferente`)
    REFERENCES `pruebatelepark`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`TipoParentesco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`TipoParentesco` (
  `idPersona` INT NOT NULL,
  `idPersonaEP` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersona`, `idPersonaEP`),
  INDEX `fk_Persona_has_Persona_EP_Persona_EP1_idx` (`idPersonaEP` ASC) VISIBLE,
  INDEX `fk_Persona_has_Persona_EP_Persona1_idx` (`idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_has_Persona_EP_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `pruebatelepark`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Persona_EP_Persona_EP1`
    FOREIGN KEY (`idPersonaEP`)
    REFERENCES `pruebatelepark`.`Persona_EP` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`ObraSocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`ObraSocial` (
  `idObraSocial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `esEstatal` TINYINT NULL,
  PRIMARY KEY (`idObraSocial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`Medicamento` (
  `idMedicamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `esAntiparkinsoniano` TINYINT NULL,
  `esLevodopa` TINYINT NULL,
  PRIMARY KEY (`idMedicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`IndicacionMedicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`IndicacionMedicamento` (
  `idIndicacion` INT NOT NULL AUTO_INCREMENT,
  `cantidadMiligramos` INT NULL,
  `estaVigente` TINYINT NULL,
  `fechaPrescripcion` DATE NULL,
  `horaDeToma` TIME NULL,
  `idPersonaEP` INT NOT NULL,
  `idMedicamento` INT NOT NULL,
  `borrado` TINYINT NOT NULL,
  PRIMARY KEY (`idIndicacion`),
  INDEX `fk_IndicacionMedicamento_Persona_EP1_idx` (`idPersonaEP` ASC) VISIBLE,
  INDEX `fk_IndicacionMedicamento_Medicamento1_idx` (`idMedicamento` ASC) VISIBLE,
  CONSTRAINT `fk_IndicacionMedicamento_Persona_EP1`
    FOREIGN KEY (`idPersonaEP`)
    REFERENCES `pruebatelepark`.`Persona_EP` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IndicacionMedicamento_Medicamento1`
    FOREIGN KEY (`idMedicamento`)
    REFERENCES `pruebatelepark`.`Medicamento` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`Enfermedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`Enfermedad` (
  `idEnfermedad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEnfermedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`Diagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`Diagnostico` (
  `idDiagnostico` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `idPersonaEP` INT NOT NULL,
  `idEnfermedad` INT NOT NULL,
  `borrado` TINYINT NOT NULL,
  PRIMARY KEY (`idDiagnostico`),
  INDEX `fk_Diagnostico_Persona_EP1_idx` (`idPersonaEP` ASC) VISIBLE,
  INDEX `fk_Diagnostico_Enfermedad1_idx` (`idEnfermedad` ASC) VISIBLE,
  CONSTRAINT `fk_Diagnostico_Persona_EP1`
    FOREIGN KEY (`idPersonaEP`)
    REFERENCES `pruebatelepark`.`Persona_EP` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diagnostico_Enfermedad1`
    FOREIGN KEY (`idEnfermedad`)
    REFERENCES `pruebatelepark`.`Enfermedad` (`idEnfermedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`Evolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`Evolucion` (
  `idEvolucion` INT NOT NULL AUTO_INCREMENT,
  `escalaEvolucion` INT NOT NULL,
  `fecha` DATE NULL,
  `idPersonaEP` INT NOT NULL,
  `borrado` TINYINT NOT NULL,
  PRIMARY KEY (`idEvolucion`),
  INDEX `fk_Evolucion_Persona_EP1_idx` (`idPersonaEP` ASC) VISIBLE,
  CONSTRAINT `fk_Evolucion_Persona_EP1`
    FOREIGN KEY (`idPersonaEP`)
    REFERENCES `pruebatelepark`.`Persona_EP` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`TipoEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`TipoEvento` (
  `idTipoEvento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `desactivaTaller` TINYINT NULL,
  `borrado` TINYINT NOT NULL,
  PRIMARY KEY (`idTipoEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `fechaDesde` DATE NULL,
  `fechaHasta` DATE NULL,
  `motivo` VARCHAR(256) NULL,
  `idPersonaEP` INT NOT NULL,
  `idTipoEvento` INT NOT NULL,
  `borrado` TINYINT NOT NULL,
  INDEX `fk_Evento_Persona_EP1_idx` (`idPersonaEP` ASC) VISIBLE,
  INDEX `fk_Evento_TipoEvento1_idx` (`idTipoEvento` ASC) VISIBLE,
  PRIMARY KEY (`idEvento`),
  CONSTRAINT `fk_Evento_Persona_EP1`
    FOREIGN KEY (`idPersonaEP`)
    REFERENCES `pruebatelepark`.`Persona_EP` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_TipoEvento1`
    FOREIGN KEY (`idTipoEvento`)
    REFERENCES `pruebatelepark`.`TipoEvento` (`idTipoEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`auth_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`django_content_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`auth_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT(11) NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `pruebatelepark`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 81
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`auth_group_permissions` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `pruebatelepark`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `pruebatelepark`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`auth_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`auth_user_groups` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `pruebatelepark`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `pruebatelepark`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`auth_user_user_permissions` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `pruebatelepark`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `pruebatelepark`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`django_admin_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT(5) UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC) VISIBLE,
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `pruebatelepark`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `pruebatelepark`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`django_migrations` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`OS` (
  `idOS` INT NOT NULL AUTO_INCREMENT,
  `idPersonaEP` INT NOT NULL,
  `idObraSocial` INT NOT NULL,
  `borrado` TINYINT NOT NULL,
  PRIMARY KEY (`idOS`),
  INDEX `fk_OS_Persona_EP1_idx` (`idPersonaEP` ASC) VISIBLE,
  INDEX `fk_OS_ObraSocial1_idx` (`idObraSocial` ASC) VISIBLE,
  CONSTRAINT `fk_OS_Persona_EP1`
    FOREIGN KEY (`idPersonaEP`)
    REFERENCES `pruebatelepark`.`Persona_EP` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_ObraSocial1`
    FOREIGN KEY (`idObraSocial`)
    REFERENCES `pruebatelepark`.`ObraSocial` (`idObraSocial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`Taller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`Taller` (
  `idTaller` INT NOT NULL AUTO_INCREMENT,
  `tipoTaller` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTaller`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`ClaseTaller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`ClaseTaller` (
  `idClaseTaller` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `virtual` TINYINT NOT NULL,
  `idTaller` INT NOT NULL,
  PRIMARY KEY (`idClaseTaller`),
  INDEX `fk_ClaseTaller_Taller1_idx` (`idTaller` ASC) VISIBLE,
  CONSTRAINT `fk_ClaseTaller_Taller1`
    FOREIGN KEY (`idTaller`)
    REFERENCES `pruebatelepark`.`Taller` (`idTaller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`Comportamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`Comportamiento` (
  `idComportamiento` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idComportamiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`AsistenciaTaller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`AsistenciaTaller` (
  `idAsistenciaTaller` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `idPersonaEP` INT NOT NULL,
  `idClaseTaller` INT NOT NULL,
  `idComportamiento` INT NULL,
  PRIMARY KEY (`idAsistenciaTaller`),
  INDEX `fk_AsistenciaTaller_Persona_EP1_idx` (`idPersonaEP` ASC) VISIBLE,
  INDEX `fk_AsistenciaTaller_ClaseTaller1_idx` (`idClaseTaller` ASC) VISIBLE,
  INDEX `fk_AsistenciaTaller_Comportamiento1_idx` (`idComportamiento` ASC) VISIBLE,
  CONSTRAINT `fk_AsistenciaTaller_Persona_EP1`
    FOREIGN KEY (`idPersonaEP`)
    REFERENCES `pruebatelepark`.`Persona_EP` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsistenciaTaller_ClaseTaller1`
    FOREIGN KEY (`idClaseTaller`)
    REFERENCES `pruebatelepark`.`ClaseTaller` (`idClaseTaller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsistenciaTaller_Comportamiento1`
    FOREIGN KEY (`idComportamiento`)
    REFERENCES `pruebatelepark`.`Comportamiento` (`idComportamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`Actividad` (
  `idActividad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idTaller` INT NOT NULL,
  PRIMARY KEY (`idActividad`),
  INDEX `fk_Actividad_Taller1_idx` (`idTaller` ASC) VISIBLE,
  CONSTRAINT `fk_Actividad_Taller1`
    FOREIGN KEY (`idTaller`)
    REFERENCES `pruebatelepark`.`Taller` (`idTaller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`FactorGlobal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`FactorGlobal` (
  `idFactorGlobal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFactorGlobal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`FactorClase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`FactorClase` (
  `idClaseTaller` INT NOT NULL,
  `idFactorGlobal` INT NOT NULL,
  PRIMARY KEY (`idClaseTaller`, `idFactorGlobal`),
  INDEX `fk_ClaseTaller_has_FactorGlobal_FactorGlobal1_idx` (`idFactorGlobal` ASC) VISIBLE,
  INDEX `fk_ClaseTaller_has_FactorGlobal_ClaseTaller1_idx` (`idClaseTaller` ASC) VISIBLE,
  CONSTRAINT `fk_ClaseTaller_has_FactorGlobal_ClaseTaller1`
    FOREIGN KEY (`idClaseTaller`)
    REFERENCES `pruebatelepark`.`ClaseTaller` (`idClaseTaller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClaseTaller_has_FactorGlobal_FactorGlobal1`
    FOREIGN KEY (`idFactorGlobal`)
    REFERENCES `pruebatelepark`.`FactorGlobal` (`idFactorGlobal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`ActividadRealizada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`ActividadRealizada` (
  `idActividad` INT NOT NULL,
  `idClaseTaller` INT NOT NULL,
  PRIMARY KEY (`idActividad`, `idClaseTaller`),
  INDEX `fk_Actividad_has_ClaseTaller_ClaseTaller1_idx` (`idClaseTaller` ASC) VISIBLE,
  INDEX `fk_Actividad_has_ClaseTaller_Actividad1_idx` (`idActividad` ASC) VISIBLE,
  CONSTRAINT `fk_Actividad_has_ClaseTaller_Actividad1`
    FOREIGN KEY (`idActividad`)
    REFERENCES `pruebatelepark`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_has_ClaseTaller_ClaseTaller1`
    FOREIGN KEY (`idClaseTaller`)
    REFERENCES `pruebatelepark`.`ClaseTaller` (`idClaseTaller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`UnidadObservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`UnidadObservacion` (
  `idUnidadObservacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUnidadObservacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`VariableUO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`VariableUO` (
  `idVariableUO` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idComportamiento` INT NOT NULL,
  `idUnidadObservacion` INT NOT NULL,
  PRIMARY KEY (`idVariableUO`),
  INDEX `fk_VariableUO_Comportamiento1_idx` (`idComportamiento` ASC) VISIBLE,
  INDEX `fk_VariableUO_UnidadObservacion1_idx` (`idUnidadObservacion` ASC) VISIBLE,
  CONSTRAINT `fk_VariableUO_Comportamiento1`
    FOREIGN KEY (`idComportamiento`)
    REFERENCES `pruebatelepark`.`Comportamiento` (`idComportamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VariableUO_UnidadObservacion1`
    FOREIGN KEY (`idUnidadObservacion`)
    REFERENCES `pruebatelepark`.`UnidadObservacion` (`idUnidadObservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebatelepark`.`ValorVariableUO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebatelepark`.`ValorVariableUO` (
  `idValorVariableUO` INT NOT NULL AUTO_INCREMENT,
  `valor` VARCHAR(45) NOT NULL,
  `idVariableUO` INT NOT NULL,
  PRIMARY KEY (`idValorVariableUO`),
  INDEX `fk_ValorVariableUO_VariableUO1_idx` (`idVariableUO` ASC) VISIBLE,
  CONSTRAINT `fk_ValorVariableUO_VariableUO1`
    FOREIGN KEY (`idVariableUO`)
    REFERENCES `pruebatelepark`.`VariableUO` (`idVariableUO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
