# Generated by Django 6.0.6 on 2026-07-04 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('idlocalidad', models.AutoField(db_column='idLocalidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('codigopostal', models.IntegerField(db_column='codigoPostal')),
            ],
            options={
                'db_table': 'localidad',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idmunicipio', models.AutoField(db_column='idMunicipio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('provincia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('iddireccion', models.AutoField(db_column='idDireccion', primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, max_length=45, null=True)),
                ('departamento', models.CharField(blank=True, max_length=45, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('idlocalidad', models.ForeignKey(blank=True, db_column='idLocalidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.localidad')),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='idmunicipio',
            field=models.ForeignKey(blank=True, db_column='idMunicipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.municipio'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=35)),
                ('borrado', models.IntegerField(db_column='borrado')),
                ('espaciente', models.IntegerField(db_column='esPaciente')),
                ('iddireccion', models.ForeignKey(blank=True, db_column='idDireccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.direccion')),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='PersonaEp',
            fields=[
                ('activataller', models.IntegerField(blank=True, db_column='activaTaller', null=True)),
                ('escolaridadcompleta', models.IntegerField(blank=True, db_column='escolaridadCompleta', null=True)),
                ('fechainicio', models.DateTimeField(db_column='fechaInicio')),
                ('fechanacimiento', models.DateField(db_column='fechaNacimiento')),
                ('maximaescolaridadalcanzada', models.CharField(blank=True, db_column='maximaEscolaridadAlcanzada', max_length=45, null=True)),
                ('sexo', models.CharField(max_length=45)),
                ('tieneacompanante', models.IntegerField(db_column='tieneAcompanante')),
                ('tienecuidador', models.IntegerField(db_column='tieneCuidador')),
                ('vivesolo', models.IntegerField(db_column='viveSolo')),
                ('ocupacionprevia', models.CharField(db_column='ocupacionPrevia', max_length=45)),
                ('ocupacionactual', models.CharField(db_column='ocupacionActual', max_length=45)),
                ('idpersona', models.OneToOneField(db_column='idPersona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personas.persona')),
                ('idreferente', models.ForeignKey(db_column='idReferente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.persona')),
            ],
            options={
                'db_table': 'persona_ep',
                'unique_together': {('idpersona', 'idreferente')},
            },
        ),
        migrations.CreateModel(
            name='Tipoparentesco',
            fields=[
                ('idpersona', models.OneToOneField(db_column='idPersona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personas.persona')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('idpersonaep', models.ForeignKey(db_column='idPersonaEP', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.personaep')),
            ],
            options={
                'db_table': 'tipoparentesco',
                'unique_together': {('idpersona', 'idpersonaep')},
            },
        ),
    ]
