# Generated by Django 6.0.6 on 2026-07-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_personaep_mti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaep',
            name='fechanacimiento',
        ),
        migrations.RemoveField(
            model_name='personaep',
            name='sexo',
        ),
        migrations.AddField(
            model_name='persona',
            name='fechanacimiento',
            field=models.DateField(db_column='fechaNacimiento', default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(default='', max_length=45),
        ),
    ]
