# Generated by Django 6.0.6 on 2026-07-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_remove_personaep_fechanacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechanacimiento',
            field=models.DateField(db_column='fechaNacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(max_length=45),
        ),
    ]
