# Generated by Django 6.0.6 on 2026-08-17 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_alter_persona_fechanacimiento_alter_persona_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idprovincia', models.AutoField(db_column='idProvincia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='provincia',
        ),
        migrations.AddField(
            model_name='municipio',
            name='idprovincia',
            field=models.ForeignKey(blank=True, db_column='idProvincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.provincia'),
        ),
    ]
