# Generated by Django 6.0.6 on 2026-08-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_provincia_remove_municipio_provincia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='codigopostal',
            field=models.IntegerField(blank=True, db_column='codigoPostal', null=True),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
