# Generated by Django 6.0.6 on 2026-08-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_alter_localidad_codigopostal_alter_localidad_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='codigopostal',
            field=models.IntegerField(db_column='codigoPostal'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
