# Generated by Django 6.0.6 on 2026-08-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_alter_localidad_codigopostal_alter_localidad_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='id_georef',
            field=models.CharField(blank=True, db_column='idGeoref', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='id_georef',
            field=models.CharField(blank=True, db_column='idGeoref', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provincia',
            name='id_georef',
            field=models.CharField(blank=True, db_column='idGeoref', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='codigopostal',
            field=models.IntegerField(blank=True, db_column='codigoPostal', null=True),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
