# Generated by Django 6.0.6 on 2026-08-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_localidad_id_georef_municipio_id_georef_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='espaciente',
        ),
    ]
