# Generated by Django 6.0.6 on 2026-09-03 15:42

from django.db import migrations, models


def verificar_y_convertir_borrado(apps, schema_editor):
    Persona = apps.get_model('personas', 'Persona')
    valores = set(v['borrado'] for v in Persona.objects.values('borrado').distinct())
    if not valores.issubset({0, 1}):
        raise RuntimeError(
            f"Valores inesperados en personas.Persona.borrado: {sorted(valores)}. "
            "Se esperaban únicamente 0 y 1; migración abortada sin cambios."
        )
    Persona.objects.filter(borrado=0).update(borrado=False)
    Persona.objects.exclude(borrado=0).update(borrado=True)


def revertir_borrado(apps, schema_editor):
    Persona = apps.get_model('personas', 'Persona')
    Persona.objects.filter(borrado=False).update(borrado=0)
    Persona.objects.exclude(borrado=False).update(borrado=1)


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0010_remove_persona_espaciente'),
    ]

    operations = [
        migrations.RunPython(verificar_y_convertir_borrado, revertir_borrado),
        migrations.AlterField(
            model_name='persona',
            name='borrado',
            field=models.BooleanField(db_column='borrado', default=False),
        ),
    ]
