# Generated by Django 6.0.6 on 2026-09-03 23:31

from django.db import migrations, models

CAMPOS = ('activataller', 'escolaridadcompleta', 'tieneacompanante', 'tienecuidador', 'vivesolo')


def verificar_y_convertir_campos(apps, schema_editor):
    PersonaEp = apps.get_model('personas', 'PersonaEp')
    for campo in CAMPOS:
        valores = set(v[campo] for v in PersonaEp.objects.values(campo).distinct())
        if not valores.issubset({0, 1}):
            raise RuntimeError(
                f"Valores inesperados en personas.PersonaEp.{campo}: {sorted(valores)}. "
                "Se esperaban únicamente 0 y 1; migración abortada sin cambios."
            )
        PersonaEp.objects.filter(**{campo: 0}).update(**{campo: False})
        PersonaEp.objects.exclude(**{campo: 0}).update(**{campo: True})


def revertir_campos(apps, schema_editor):
    PersonaEp = apps.get_model('personas', 'PersonaEp')
    for campo in CAMPOS:
        PersonaEp.objects.filter(**{campo: False}).update(**{campo: 0})
        PersonaEp.objects.exclude(**{campo: False}).update(**{campo: 1})


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0011_alter_persona_borrado'),
    ]

    operations = [
        migrations.RunPython(verificar_y_convertir_campos, revertir_campos),
        migrations.AlterField(
            model_name='personaep',
            name='activataller',
            field=models.BooleanField(db_column='activaTaller', default=False),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='escolaridadcompleta',
            field=models.BooleanField(db_column='escolaridadCompleta', default=False),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='tieneacompanante',
            field=models.BooleanField(db_column='tieneAcompanante', default=False),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='tienecuidador',
            field=models.BooleanField(db_column='tieneCuidador', default=False),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='vivesolo',
            field=models.BooleanField(db_column='viveSolo', default=False),
        ),
    ]