# Generated by Django 6.0.6 on 2026-09-04 (E17 — rename Municipio → Departamento)
# Fix E18: the original migration only renamed model/fields in state (db_column
# 'idMunicipio' and db_table 'municipio' were left unchanged), so the physical
# table/columns were never renamed and the FK restore failed. Added
# AlterField/AlterModelTable to capture the db_column/db_table changes.

import django.db.models.deletion
from django.db import migrations, models


def _drop_fk_localidad_municipio(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'localidad' "
            "AND REFERENCED_TABLE_NAME = 'municipio'"
        )
        for (name,) in cursor.fetchall():
            cursor.execute(f"ALTER TABLE `localidad` DROP FOREIGN KEY `{name}`")


def _restore_fk_localidad_municipio(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE `localidad` ADD CONSTRAINT `localidad_idmunicipio_fk` "
            "FOREIGN KEY (`idMunicipio`) REFERENCES `municipio` (`idMunicipio`)"
        )


def _drop_fk_localidad_departamento(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'localidad' "
            "AND REFERENCED_TABLE_NAME = 'departamento'"
        )
        for (name,) in cursor.fetchall():
            cursor.execute(f"ALTER TABLE `localidad` DROP FOREIGN KEY `{name}`")


def _restore_fk_localidad_departamento(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE `localidad` ADD CONSTRAINT `localidad_iddepartamento_fk` "
            "FOREIGN KEY (`iddepartamento`) REFERENCES `departamento` (`iddepartamento`)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0012_alter_personaep_activataller_and_more'),
    ]

    operations = [
        migrations.RunPython(_drop_fk_localidad_municipio, _restore_fk_localidad_municipio),
        migrations.RenameModel(
            old_name='Municipio',
            new_name='Departamento',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='idmunicipio',
            new_name='iddepartamento',
        ),
        migrations.RenameField(
            model_name='localidad',
            old_name='idmunicipio',
            new_name='iddepartamento',
        ),
        migrations.AlterField(
            model_name='departamento',
            name='iddepartamento',
            field=models.AutoField(db_column='iddepartamento', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='iddepartamento',
            field=models.ForeignKey(blank=True, db_column='iddepartamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.departamento'),
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='departamento',
        ),
        migrations.RunPython(_restore_fk_localidad_departamento, _drop_fk_localidad_departamento),
    ]