# Generated by Django 6.0.6 on 2026-09-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0013_rename_municipio_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='fuente_departamento',
            field=models.CharField(blank=True, choices=[('censal', 'censal'), ('bahra', 'bahra'), ('manual', 'manual')], db_column='fuenteDepartamento', max_length=10, null=True),
        ),
    ]
