# Generated by Django 6.0.6 on 2026-09-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0014_localidad_fuente_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='id_georef',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='fuente_departamento',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='id_georef',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='id_georef',
        ),
    ]
