# Generated by Django 6.0.6 on 2026-09-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0015_remove_departamento_id_georef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='categoria',
            field=models.CharField(blank=True, db_column='categoria', default='', max_length=50),
        ),
    ]
