# Generated by Django 6.0.6 on 2026-09-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0016_localidad_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='categoria',
        ),
    ]
