# Generated by Django 6.0.6 on 2026-09-06 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0017_remove_localidad_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ('nombre',)},
        ),
    ]
