# Generated by Django 6.0.6 on 2026-10-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0019_rename_iddepartamento_departamento_id_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='id_departamento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.provincia'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='id_direccion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.localidad'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.departamento'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='id_localidad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.direccion'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_persona',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='activa_taller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='escolaridad_completa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='maxima_escolaridad_alcanzada',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='ocupacion_actual',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='ocupacion_previa',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='persona_ptr',
            field=models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, primary_key=True, serialize=False, to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='referente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='tiene_acompanante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='tiene_cuidador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personaep',
            name='vive_solo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='id_provincia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoparentesco',
            name='id_tipo_parentesco',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoparentesco',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='tipoparentesco',
            name='persona_ep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.personaep'),
        ),
    ]
